# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

###
Vector: A vector is a one dimentional array of elements.
It can be represent as a coloumn of row of element.
Example of a vector is [1,4,5,6]

Matrix: Matrix is a two-dimentioal array of elements.
It consists multiple row and coloums.
Example of a matrix is: [[2,4,5],
                         [70,5,4],
                         [5,6,3]]

**2. How to import `NumPy` library?** 

In [17]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [11]:

list_1 = [1,2,3,4,5]
a = np.array(list_1)
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

NameError: name 'np' is not defined

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [20]:
my_array = np.arange(6)
my_array

array([0, 1, 2, 3, 4, 5])

In [21]:
my_array = np.arange(6)
my_array

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [14]:
# To avoid overwriting the output, please code here 

In [22]:
my_array=np.zeros(5)
my_array

array([0., 0., 0., 0., 0.])

**6. Generate the following `matrix`.**

In [66]:
a=np.zeros(12)
a = a.reshape(3,4)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [26]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [28]:
c=np.full(5,10, dtype=float)
c

array([10., 10., 10., 10., 10.])

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [68]:
d=np.arange(52,100,2)
d

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [81]:
start=0
stop=1
step=10
h=np.linspace(0,1,10)
step_size=(stop-start)/(step-1)
print(step_size)
h

0.1111111111111111


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [33]:
s=np.arange(0,25)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
x=s.reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
s.shape=(5,5)
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [56]:
n=np.arange(0.1,2.6,0.1)
n
n=n.reshape(5,5)
n

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [78]:
x=np.linspace(0,24,25, dtype=int)
print(x)
x=x.reshape(5,5)
x

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [31]:
arange():
The arange() function generates arrays with evenly spaced values within a given interval.
It takes three arguments: start, stop, and optionally step.
The step argument specifies the spacing between values in the array.

linspace():
The linspace() function generates arrays with a specified number of evenly spaced points within a given interval.
It takes three arguments: start, stop, and num.
The num argument specifies the number of points or elements you want in the array.

**15. How to generate a single random integer number using NumPy built-in function?**

In [63]:
a=np.random.randint(0,10)
a

2

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [64]:
r = np.random.rand(7,5)
r

array([[0.40135644, 0.84028834, 0.0526868 , 0.46517285, 0.60079456],
       [0.87211884, 0.30080999, 0.32531705, 0.25037462, 0.45507038],
       [0.53796733, 0.14500623, 0.29893293, 0.23927416, 0.04543416],
       [0.64264029, 0.70148484, 0.64450697, 0.20836713, 0.27039176],
       [0.46873046, 0.20409167, 0.31017147, 0.2114312 , 0.63703858],
       [0.99739402, 0.67455178, 0.90406031, 0.52626118, 0.7856129 ],
       [0.19587296, 0.0904546 , 0.61111642, 0.76672612, 0.14115602]])

[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [65]:
m=np.eye(5)*5
m

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 